// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqlWxUHDDEfAl2GMu9eRq_ceJi-yhnoCs',
    appId: '1:746030524765:web:21a3520ebf81e9032c20b4',
    messagingSenderId: '746030524765',
    projectId: 'nocturna1',
    authDomain: 'nocturna1.firebaseapp.com',
    storageBucket: 'nocturna1.appspot.com',
    measurementId: 'G-V612B8L4HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIhcEVK4DTffkRA9neh_sQWf-_ox6ER-w',
    appId: '1:746030524765:android:065ac34bce014db22c20b4',
    messagingSenderId: '746030524765',
    projectId: 'nocturna1',
    storageBucket: 'nocturna1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3OvhViVkjrbTbNsdjFnEMGuTk4h910M',
    appId: '1:746030524765:ios:ca93c94f05866e4b2c20b4',
    messagingSenderId: '746030524765',
    projectId: 'nocturna1',
    storageBucket: 'nocturna1.appspot.com',
    iosBundleId: 'com.example.nocturna',
  );
}
